<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find ros2_fra2mo)/urdf/utility_macro.xacro" />

  <xacro:macro name="fra2mo_base" >

    <xacro:property name="base_height" value="0.180" /> 
    <xacro:property name="base_radius" value="0.11" /> 
    <xacro:property name="base_mass" value="15" />
    <xacro:property name="wheel_mass" value="2.5" />
    <xacro:property name="wheel_radius" value="0.035" /> 
    <xacro:property name="wheel_axle" value="0.130" /> 
   
    <link name="base_footprint">
    </link>

    <link name="base_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${base_mass}" />
        <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
      </inertial>
      <visual> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_body.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Blue" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision>
        <geometry>
          <cylinder length="${base_height}" radius="0.09" /> 
        </geometry>
        <origin xyz="0 0.0 ${(base_height/2.0)-0.04}" rpy="0 0 0" />
      </collision>
      <collision>
        <geometry>
          <sphere radius="0.019" />
        </geometry>
        <origin xyz="-0.0825 0.0 -0.04" rpy="0 0 0" />
      </collision>       
    </link>

    <link name="left_wheel_link">
      <visual> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Black" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision> 
        <geometry>
          <cylinder length="0.02" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

    <link name="right_wheel_link">
      <visual> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Black"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision> 
        <geometry>
          <cylinder length="0.02" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

    <link name="d435_link">
    </link>
    <link name="lidar_link" />

    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0.0 0.0 0.059" rpy="0 0 0" />
    </joint>
    <joint name="left_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="left_wheel_link" />
      <origin xyz="0.04025 0.062 -0.024" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="1000" velocity="100" />
      <dynamics damping="0.1" friction="0.01" />
    </joint>
    <joint name="right_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="right_wheel_link" />
      <origin xyz="0.04025 -0.062 -0.024" rpy="0 0 ${-M_PI}" />
      <axis xyz="0 -1 0" />
      <limit effort="1000" velocity="100" />
      <dynamics damping="0.1" friction="0.01" />
    </joint>
    <joint name="d435_joint" type="fixed">
      <parent link="base_link" />
      <child link="d435_link" />
      <origin xyz="0.090925 0.0 0.06670" rpy="0 0 0" />
    </joint>
    <joint name="lidar_joint" type="fixed">
      <parent link="base_link" />
      <child link="lidar_link" />
      <origin xyz="0.0 0.0 0.125" rpy="0 0 0" />
    </joint>

    <gazebo reference="base_link">
      <mu1>0.0</mu1>
      <mu2>0.0</mu2>
      <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="left_wheel_link">
      <mu1>200.0</mu1>
      <mu2>200.0</mu2>
      <kp>500000.0</kp>
      <kd>10.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>0.1</maxVel>
      <fdir1>1 0 0</fdir1>
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="right_wheel_link">
      <mu1>200.0</mu1>
      <mu2>200.0</mu2>
      <kp>500000.0</kp>
      <kd>10.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>0.1</maxVel>
      <fdir1>1 0 0</fdir1>
      <material>Gazebo/Black</material>
    </gazebo>

    <transmission name="left_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="left_wheel_joint" />
      <actuator name="left_wheel_joint_motor">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <transmission name="right_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="right_wheel_joint" />
      <actuator name="right_wheel_joint_motor">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>

    <gazebo>
      <plugin name="ignition::gazebo::systems::DiffDrive" filename="libignition-gazebo-diff-drive-system.so">
        <left_joint>left_wheel_joint</left_joint>
        <right_joint>right_wheel_joint</right_joint>
        <wheel_separation>${wheel_axle}</wheel_separation>
        <wheel_radius>${wheel_radius}</wheel_radius>
        <odom_publish_frequency>50</odom_publish_frequency>
        <topic>cmd_vel</topic>
      </plugin>
    </gazebo>

    <gazebo>
        <plugin filename="libignition-gazebo-detachable-joint-system.so"
                name="ignition::gazebo::systems::DetachableJoint">
            <parent_link>base_footprint</parent_link>
            <child_model>order_can</child_model>
            <child_model_link>l</child_model_link>
            <child_link>l</child_link>
            <attach_topic>/fra2mo/bar/gripper/attach</attach_topic>
            <detach_topic>/fra2mo/bar/gripper/detach</detach_topic>
        </plugin>
    </gazebo>

  </xacro:macro>
</robot>